name: Build Android APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Gerekli Paketleri Yükle (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Buildozer ile APK Üret
        run: |
          # Mobile klasörüne girip işlemi orada yapıyoruz
          cd mobile
          # Buildozer'a otomatik 'evet' demesi için 'yes' komutunu kullanıyoruz
          yes | buildozer android debug

      - name: APK'yı Yükle
        uses: actions/upload-artifact@v4
        with:
          name: python-toolbox-apk
          path: mobile/bin/*.apk
